-- Target API Manager — Supabase schema
-- Paste this whole file into Supabase Dashboard → SQL Editor → Run.
-- The app talks to these tables with the SERVICE ROLE key (bypasses RLS),
-- so no policies are needed and the anon key can't read/write this data.

drop function if exists public.utc_now() cascade;
create function public.utc_now() returns text
language sql stable as $$
  select to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS');
$$;

create table if not exists settings (
  key text primary key,
  value text
);

create table if not exists api_keys (
  id bigint generated by default as identity primary key,
  provider text not null default 'other',
  account_name text not null,
  account_email text not null default '',
  api_key_enc text not null,
  base_url text not null default '',
  usage_limit double precision not null default 0,
  usage_period text not null default 'monthly',
  usage_hour integer not null default 9,
  provider_usage double precision,
  provider_limit double precision,
  disabled integer not null default 0,
  status text not null default 'unknown',
  status_detail text not null default '',
  last_checked_at text,
  last_error text,
  created_at text not null default public.utc_now(),
  updated_at text not null default public.utc_now()
);

create table if not exists key_models (
  id bigint generated by default as identity primary key,
  key_id bigint not null references api_keys(id) on delete cascade,
  model text not null,
  token_limit double precision not null default 0,
  period text not null default 'daily',
  usage_hour integer not null default 0,
  rpm double precision not null default 0,
  rpd double precision not null default 0,
  tpm double precision not null default 0,
  enabled integer not null default 1,
  unique(key_id, model)
);

create table if not exists key_usage_hourly (
  id bigint generated by default as identity primary key,
  key_id bigint not null,
  model text not null default '',
  day text not null,
  hour integer not null,
  hits integer not null default 0,
  tokens double precision not null default 0,
  unique(key_id, model, day, hour)
);

create table if not exists key_checks (
  id bigint generated by default as identity primary key,
  key_id bigint not null,
  status text not null,
  error text,
  response_ms integer,
  ratelimit text,
  provider_usage text,
  check_at text not null default public.utc_now()
);

create table if not exists kaggle_accounts (
  id bigint generated by default as identity primary key,
  label text not null,
  username text not null,
  api_key_enc text not null,
  weekly_gpu_quota_h double precision not null default 30,
  week_reset_day integer not null default 0,
  remaining_override_h double precision,
  override_set_at text,
  disabled integer not null default 0,
  refresh_token_enc text,
  quota_used_h double precision not null default 0,
  quota_reserved_h double precision not null default 0,
  quota_total_h double precision,
  quota_refresh_at text,
  quota_source text,
  created_at text not null default public.utc_now(),
  updated_at text not null default public.utc_now()
);

create table if not exists kaggle_sessions (
  id bigint generated by default as identity primary key,
  account_id bigint not null,
  slug text not null,
  label text not null default '',
  type text not null default 'notebook',
  status text not null default 'unknown',
  status_detail text not null default '',
  status_changed_at text,
  running_since text,
  last_checked_at text,
  dead integer not null default 0,
  dead_at text,
  paused integer not null default 0,
  auto_switch integer not null default 1,
  plexus_url text not null default '',
  plexus_status text not null default 'unknown',
  plexus_error text not null default '',
  created_at text not null default public.utc_now(),
  updated_at text not null default public.utc_now()
);

create table if not exists kaggle_session_events (
  id bigint generated by default as identity primary key,
  session_id bigint not null,
  account_id bigint,
  from_status text,
  to_status text,
  note text,
  at text not null default public.utc_now()
);

create table if not exists gpu_usage_weekly (
  id bigint generated by default as identity primary key,
  account_id bigint not null,
  week_start text not null,
  seconds_run double precision not null default 0,
  unique(account_id, week_start)
);

create table if not exists sessions (
  token text primary key,
  created_at text not null default public.utc_now(),
  expires_at text
);

create table if not exists general_keys (
  id bigint generated by default as identity primary key,
  name text not null,
  note text not null default '',
  key_hash text not null,
  secret_enc text,
  enabled integer not null default 1,
  created_at text not null default public.utc_now(),
  last_used_at text
);

create table if not exists general_key_logs (
  id bigint generated by default as identity primary key,
  gk_id bigint not null,
  key_id bigint,
  hits integer not null default 1,
  tokens integer not null default 0,
  day text not null default '',
  hour integer not null default 0,
  at text not null default public.utc_now()
);

-- Tunnel URL published by the Plexus Kaggle notebook (row id=1, column public_url).
create table if not exists plexus_endpoint (
  id bigint primary key,
  public_url text,
  updated_at text not null default public.utc_now()
);

create index if not exists idx_usage_key_day on key_usage_hourly(key_id, day);
create index if not exists idx_usage_model on key_usage_hourly(key_id, model, day);
create index if not exists idx_models_key on key_models(key_id);
create index if not exists idx_checks_key on key_checks(key_id, check_at);
create index if not exists idx_events_session on kaggle_session_events(session_id, at);
create index if not exists idx_gpu_account on gpu_usage_weekly(account_id, week_start);
create index if not exists idx_gk_logs on general_key_logs(gk_id, at);
create index if not exists idx_gk_logs_day on general_key_logs(gk_id, day);
create index if not exists idx_gk_logs_k on general_key_logs(gk_id, key_id, day);

-- Lock down: only the service-role key (used by the server) can touch these.
alter table settings enable row level security;
alter table api_keys enable row level security;
alter table key_models enable row level security;
alter table key_usage_hourly enable row level security;
alter table key_checks enable row level security;
alter table kaggle_accounts enable row level security;
alter table kaggle_sessions enable row level security;
alter table kaggle_session_events enable row level security;
alter table gpu_usage_weekly enable row level security;
alter table sessions enable row level security;
alter table general_keys enable row level security;
alter table general_key_logs enable row level security;
alter table plexus_endpoint enable row level security;